.TH IPAAS: "8" "" "May 2013" "May 2013"

.SH NAME
firebat \- program for starting iptables firewall on startup
.PP
.SH DESCRIPTION
This program is starting iptables rules stored in /etc/ipaas at system boot.

.SH USAGE
.TP
service firebat fBstart|stop|restart\fR
.TP
start firebat
.TP
stop firebat

.SH AUTHOR
.PP
firebat is Copyright 2013-2017, Filip Dorosz

.PP
firebat manual written by Filip Dorosz <filip.dorosz@rapidrage\&.org>
