#!/bin/sh
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License version 3,
#    as published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

IPTBLS=/sbin/iptables

start_firewall(){
if [ -s "/etc/firebat" ]; then
    . "/etc/firebat"
else
	echo "Could not find rules file!"
	exit 1
fi
}

stop_firewall(){
$IPTBLS -F
$IPTBLS -X
$IPTBLS -t nat -F
$IPTBLS -t nat -X
$IPTBLS -t mangle -F
$IPTBLS -t mangle -X
$IPTBLS -P INPUT ACCEPT
$IPTBLS -P FORWARD ACCEPT
$IPTBLS -P OUTPUT ACCEPT
}

case "$1" in
start)

	start_firewall

    ;;
stop)

	stop_firewall

    ;;
restart)

	stop_firewall
	start_firewall

    ;;
*)
    echo "Usage: /lib/firebat/firebat-init {start|stop|restart}"
    exit 1
    ;;
esac

