#!/bin/sh
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License version 3,
#    as published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

IPTBLS=/sbin/iptables

start_firewall(){
if [ -s "/etc/firebat/up.rules" ]; then
	. "/etc/firebat/up.rules"
else
	echo "Could not find: up.rules"
	exit 1
fi
}

stop_firewall(){
if [ -s "/etc/firebat/up.rules" ]; then
	. "/etc/firebat/down.rules"
else
	echo "Could not find: down.rules"
fi
}

case "$1" in
start)

	start_firewall

    ;;
stop)

	stop_firewall

    ;;
restart)

	stop_firewall
	start_firewall

    ;;
*)
    echo "Usage: /lib/firebat/firebat-init {start|stop|restart}"
    exit 1
    ;;
esac

